[build]
  command = "yarn build"
  publish = "dist"

[template.environment]
  STATUSKIT_PAGE_TITLE = "Dashy"
  STATUSKIT_COMPANY_LOGO = "https://raw.githubusercontent.com/Lissy93/dashy/master/docs/assets/logo.png"
  STATUSKIT_SUPPORT_CONTACT_LINK = "https://dashy.as93.net"
  STATUSKIT_RESOURCES_LINK = "https://github.com/Lissy93/dashy/tree/master/docs"
  