# Generates an image showing profile picture of everyone who'se contributed to Dashy
# Which is embeded in the Readme Credits section, as they deserve some recognition
name: Contributors
on:
  schedule:
    - cron: '0 1 * * 0' # At 01:00 on Sunday.
  push:
    branches:
      - master
jobs:
  contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: bubkoo/contributors-list@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          svgPath: docs/assets/CONTRIBUTORS.svg
