# Adds a comment to new PRs, showing the compressed size and size difference of new code
name: 🌈 Get Compressed Size
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: preactjs/compressed-size-action@v2
      with:
        repo-token: ${{ secrets.BOT_GITHUB_TOKEN }}
        pattern: "./dist/**/**"
