# Action to keep cloud-specific, deployment-ready branched in sync with master
name: Sync Deployment Branches
on:
  workflow_dispatch: # Manual dispatch
  schedule:
  - cron: '0 1 * * 0' # At 01:00 on Sunday.
jobs:
  sync-deploy-cloudflare:
    runs-on: ubuntu-latest
    name: Sync latest commits from master
    steps:
    - name: Checkout master
      uses: actions/checkout@v2
      with:
        ref:  master
    - name: Pull master into deploy Cloudflare branch
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.0
      with:
        target_sync_branch: deploy_cloudflare
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}
        upstream_sync_branch: master
        upstream_sync_repo: lissy93/dashy
        upstream_repo_access_token: ${{ secrets.GITHUB_TOKEN }}
        
  sync-deploy-platform-sh:
    runs-on: ubuntu-latest
    name: Sync master with Platform SH branch
    steps:
    - name: Checkout master
      uses: actions/checkout@v2
      with:
        ref:  master
    - name: Pull master into deploy Platform SH branch
      id: sync-psh
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.0
      with:
        target_sync_branch: deploy_platform-sh
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}
        upstream_sync_branch: master
        upstream_sync_repo: lissy93/dashy
        upstream_repo_access_token: ${{ secrets.GITHUB_TOKEN }}

  sync-deploy-digital-ocean:
    runs-on: ubuntu-latest
    name: Sync master with Digital Ocean branch
    steps:
    - name: Checkout master
      uses: actions/checkout@v2
      with:
        ref:  master
    - name: Pull master into deploy Digital Ocean branch
      id: sync-do
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.0
      with:
        target_sync_branch: deploy_digital-ocean
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}
        upstream_sync_branch: master
        upstream_sync_repo: lissy93/dashy
        upstream_repo_access_token: ${{ secrets.GITHUB_TOKEN }}

  sync-deploy-render:
    runs-on: ubuntu-latest
    name: Sync master with Render branch
    steps:
    - name: Checkout master
      uses: actions/checkout@v2
      with:
        ref:  master
    - name: Pull master into deploy Render branch
      id: sync-render
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.0
      with:
        target_sync_branch: deploy_render
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}
        upstream_sync_branch: master
        upstream_sync_repo: lissy93/dashy
        upstream_repo_access_token: ${{ secrets.GITHUB_TOKEN }}

