# Uses the contents of the ./docs directory for Dashy's GH Wiki page
name: Wiki Sync
on:
  workflow_dispatch: # Manual dispatch
  schedule:
    - cron: '0 1 * * 0' # At 01:00 on Sunday.
jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Sync Wiki
      uses: cmbrose/github-docs-to-wiki@v0.24
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        defaultBranch: master
        rootDocsFolder: ./docs
        convertRootReadmeToHomePage: true
        useHeaderForWikiName: true
        customCommitMessageFormat: ':gem: Chore: Sync Docs to GH Wiki'
